### ISSUE TITLE
bucket items don't get recognized instantly

### ISSUE THREAD

**Issue by FireBladeHunter** [McPlayHDnet/ForceItemBattle#44]
you have to click on the item, even though it is already in your inventory (e.g. Bucket of Cod)

**Comment by stupxd** [comment]
Things to look for when fixing:
1. Consume event (after drinking milk bucket, if you have "Bucket" as an item to find.
2. Interact event (right click block) - for lava/powder snow/water buckets
3. Interact entity (not sure if it works cuz I never managed to make it work) - for Fish bucket, Milk bucket etc.
I think should be all cases

**Comment by realthreeseconds** [comment]
> Things to look for when fixing:
> 
> 1. Consume event (after drinking milk bucket, if you have "Bucket" as an item to find.
> 2. Interact event (right click block) - for lava/powder snow/water buckets
> 3. Interact entity (not sure if it works cuz I never managed to make it work) - for Fish bucket, Milk bucket etc.
>    I think should be all cases

The Bucket stuff is handled by the "BucketEvent", e.g. for Interact with entities its PlayerBucketEntityEvent and for fill/empty there is a seperate event (PlayerBucket-Fill/Empty-Event)

**Comment by stupxd** [comment]
Right clicking bottle on beehive / water does not work either
