### ISSUE TITLE
fix obtaining item without using materials

### ISSUE THREAD

**Issue by FireBladeHunter** [McPlayHDnet/ForceItemBattle#48]
you can get the point for the item without wasting the materials if you just click on the crafting result with a selected item 
possible solution: check if item is inventory instead of clickevent / find a different way to implement clickevent without this issue

**Comment by realthreeseconds** [comment]
fixed -> https://github.com/McPlayHDnet/ForceItemBattle/commit/0e5a497ad6928334cd24105c05800eca27c2531d

The clickevent is still there, I just added a craft- and smithitemevent, and cancelled the clickevent inside those inventories. Should work now, for simple result-click and shift click
